### ISSUE TITLE
No Gromacs files (.gro and .top) generated by gokit.py

### ISSUE THREAD

**Issue by yongwangCPH** [gokit1/gokit#1]
I am trying to following the tutorial of 1ris, by running:
python gokit.py -attype 1 -aa_pdb 1ris.pdb -skip_glycine

and got the log
in write_CB_to_native 1ris.pdb False
sopc False skipglycine, True
 in get_side_chain_COM: 1ris.pdb False
<Chain id=A>
Excluding glycine, res =  10
Excluding glycine, res =  35
Excluding glycine, res =  47
Excluding glycine, res =  53
Excluding glycine, res =  75
Excluding glycine, res =  76
in get_back_bone_COM 1ris.pdb
in write_CB_to_native: 1ris.pdb False
See file: native_cb.pdb with  146 atoms
CB= 70 CA= 76

I could see it generated the files native_ca.pdb and native_cb.pdb, but the two folders called MD and PATH were not generated as expected. And I also didn't get any error messages. 

By the way, I had an issue to run the script with python3 which failed with
Traceback (most recent call last):
  File "/lindorffgrp-isilon/wyong/temp/GoKit/gokit/gokit.py", line 1616, in <module>
    main()
  File "/lindorffgrp-isilon/wyong/temp/GoKit/gokit/gokit.py", line 1583, in main
    X.write_CB_to_native(pdbfile,False)
  File "/lindorffgrp-isilon/wyong/temp/GoKit/gokit/gokit.py", line 251, in write_CB_to_native
    CB=self.get_side_chain_COM(pdbfile,skip_glycine)
  File "/lindorffgrp-isilon/wyong/temp/GoKit/gokit/gokit.py", line 230, in get_side_chain_COM
    COM1=np.array(COM1).reshape(len(COM1)/2,2)
TypeError: 'float' object cannot be interpreted as an integer
But this could be fixed by replacing "/" with "//" in line 178 and 230. Hope these changes are not the reason that I couldn't get the MD and PATH folders.

Any clues? 
Thanks a lot!
Yong

**Comment by gokit1** [comment]
There are compatibility issues with python3, especially while using MDTraj so would recommend sticking to python2.7 for now. Your change does not cause the issue. Are you able to run the example with python2.7?

$ cd gokit/examples/1ris_ca
$ sh command
